export const products = [
  {
    id: 1,
    name: "Sillón de Terciopelo 1",
    description: "Un sillón moderno con acabado de terciopelo.",
    price: 3799900,
    discount: 0.1,
    images: [
      "/assets/sofa-terciopelo-azul-1.jpg",
      "/assets/estanteria.webp",
      "/assets/sofa-seccional.jpg",
      "/assets/cama-dosel.webp",
    ],
    information: {
      dimensiones: "80x80x90 cm",
      estructura: "Madera y metal",
      relleno: "Espuma de alta densidad",
      patas: "Madera de haya maciza",
      tapizado: "Tela de terciopelo",
      observaciones:
        "Disponible en varios colores. El valor de los decorados y detalles personalizados no incluido.",
    },
    available: true,
    categories: ["Sofás", "Sala de estar"],
  },
  {
    id: 2,
    name: "Mesa de Centro de Mármol 1",
    description:
      "Elegante mesa de centro con superficie de mármol y base metálica.",
    price: 1500900,
    discount: 0.17,
    images: [
      "/assets/mesa-de-centro.webp",
      "/assets/sofa-terciopelo-azul-1.jpg",
      "/assets/sofa-seccional.jpg",
      "/assets/cama-dosel.webp",
    ],
    information: {
      dimensiones: "120x60x45 cm",
      estructura: "Metal cromado",
      relleno: "No aplica",
      patas: "Estructura de metal",
      tapizado: "No aplica",
      observaciones:
        "Superficie resistente a manchas. El valor de los decorados y detalles personalizados no incluido.",
    },
    available: true,
    categories: ["Mesas", "Sala de estar"],
  },
  {
    id: 3,
    name: "Sofá Seccional 1",
    description: "Amplio sofá seccional con chaise longue y tapizado de lino.",
    price: 3778103,
    discount: 0.2,
    images: [
      "/assets/sofa-seccional.jpg",
      "/assets/sofa-terciopelo-azul-1.jpg",
      "/assets/estanteria.webp",
      "/assets/mesa-de-centro.webp",
    ],
    information: {
      dimensiones: "280x180x85 cm",
      estructura: "Madera de pino",
      relleno: "Espuma y plumas",
      patas: "Madera de roble",
      tapizado: "Tela de lino",
      observaciones:
        "Funda extraíble y lavable. El valor de los decorados y detalles personalizados no incluido.",
    },
    available: true,
    categories: ["Sofás", "Sala de estar"],
  },
  {
    id: 4,
    name: "Cama con Dosel 1",
    description: "Cama elegante con dosel y cabecero tapizado.",
    price: 2518721,
    discount: 0.2,
    images: [
      "/assets/cama-dosel.webp",
      "/assets/sofa-terciopelo-azul-1.jpg",
      "/assets/estanteria.webp",
      "/assets/mesa-de-centro.webp",
    ],
    information: {
      dimensiones: "160x200x180 cm",
      estructura: "Madera y metal",
      relleno: "No aplica",
      patas: "Madera de nogal",
      tapizado: "Terciopelo en cabecero",
      observaciones:
        "No incluye colchón. El valor de los decorados y detalles personalizados no incluido.",
    },
    available: false,
    categories: ["Camas", "Dormitorio"],
  },
  {
    id: 5,
    name: "Estantería Modular 1",
    description:
      "Sistema de estanterías personalizable con módulos intercambiables.",
    price: 1049442,
    discount: 0.1,
    images: [
      "/assets/estanteria.webp",
      "/assets/sofa-terciopelo-azul-1.jpg",
      "/assets/sofa-seccional.jpg",
      "/assets/cama-dosel.webp",
    ],
    information: {
      dimensiones: "180x120x35 cm",
      estructura: "Madera de roble y metal",
      relleno: "No aplica",
      patas: "Patas ajustables de metal",
      tapizado: "No aplica",
      observaciones:
        "Fácil montaje sin herramientas. El valor de los decorados y detalles personalizados no incluido.",
    },
    available: true,
    categories: ["Almacenamiento"],
  },
  {
    id: 6,
    name: "Sillón de Terciopelo 2",
    description: "Un sillón moderno con acabado de terciopelo.",
    price: 3799900,
    discount: 0.1,
    images: [
      "/assets/sofa-terciopelo-azul-1.jpg",
      "/assets/estanteria.webp",
      "/assets/sofa-seccional.jpg",
      "/assets/cama-dosel.webp",
    ],
    information: {
      dimensiones: "80x80x90 cm",
      estructura: "Madera y metal",
      relleno: "Espuma de alta densidad",
      patas: "Madera de haya maciza",
      tapizado: "Tela de terciopelo",
      observaciones:
        "Disponible en varios colores. El valor de los decorados y detalles personalizados no incluido.",
    },
    available: true,
    categories: ["Sofás", "Sala de estar"],
  },
 {
    id: 7,
    name: "Sillón de Terciopelo 1",
    description: "Un sillón moderno con acabado de terciopelo.",
    price: 3799900,
    discount: 0.1,
    images: [
      "/assets/sofa-terciopelo-azul-1.jpg",
      "/assets/estanteria.webp",
      "/assets/sofa-seccional.jpg",
      "/assets/cama-dosel.webp",
    ],
    information: {
      dimensiones: "80x80x90 cm",
      estructura: "Madera y metal",
      relleno: "Espuma de alta densidad",
      patas: "Madera de haya maciza",
      tapizado: "Tela de terciopelo",
      observaciones:
        "Disponible en varios colores. El valor de los decorados y detalles personalizados no incluido.",
    },
    available: true,
    categories: ["Sofás", "Sala de estar"],
  },
  {
    id: 8,
    name: "Mesa de Centro de Mármol 1",
    description:
      "Elegante mesa de centro con superficie de mármol y base metálica.",
    price: 1500900,
    discount: 0.17,
    images: [
      "/assets/mesa-de-centro.webp",
      "/assets/sofa-terciopelo-azul-1.jpg",
      "/assets/sofa-seccional.jpg",
      "/assets/cama-dosel.webp",
    ],
    information: {
      dimensiones: "120x60x45 cm",
      estructura: "Metal cromado",
      relleno: "No aplica",
      patas: "Estructura de metal",
      tapizado: "No aplica",
      observaciones:
        "Superficie resistente a manchas. El valor de los decorados y detalles personalizados no incluido.",
    },
    available: true,
    categories: ["Mesas", "Sala de estar"],
  },
  {
    id: 9,
    name: "Sofá Seccional 1",
    description: "Amplio sofá seccional con chaise longue y tapizado de lino.",
    price: 3778103,
    discount: 0.2,
    images: [
      "/assets/sofa-seccional.jpg",
      "/assets/sofa-terciopelo-azul-1.jpg",
      "/assets/estanteria.webp",
      "/assets/mesa-de-centro.webp",
    ],
    information: {
      dimensiones: "280x180x85 cm",
      estructura: "Madera de pino",
      relleno: "Espuma y plumas",
      patas: "Madera de roble",
      tapizado: "Tela de lino",
      observaciones:
        "Funda extraíble y lavable. El valor de los decorados y detalles personalizados no incluido.",
    },
    available: true,
    categories: ["Sofás", "Sala de estar"],
  },
  {
    id: 10,
    name: "Cama con Dosel 1",
    description: "Cama elegante con dosel y cabecero tapizado.",
    price: 2518721,
    discount: 0.2,
    images: [
      "/assets/cama-dosel.webp",
      "/assets/sofa-terciopelo-azul-1.jpg",
      "/assets/estanteria.webp",
      "/assets/mesa-de-centro.webp",
    ],
    information: {
      dimensiones: "160x200x180 cm",
      estructura: "Madera y metal",
      relleno: "No aplica",
      patas: "Madera de nogal",
      tapizado: "Terciopelo en cabecero",
      observaciones:
        "No incluye colchón. El valor de los decorados y detalles personalizados no incluido.",
    },
    available: false,
    categories: ["Camas", "Dormitorio"],
  },
  {
    id: 11,
    name: "Estantería Modular 1",
    description:
      "Sistema de estanterías personalizable con módulos intercambiables.",
    price: 1049442,
    discount: 0.1,
    images: [
      "/assets/estanteria.webp",
      "/assets/sofa-terciopelo-azul-1.jpg",
      "/assets/sofa-seccional.jpg",
      "/assets/cama-dosel.webp",
    ],
    information: {
      dimensiones: "180x120x35 cm",
      estructura: "Madera de roble y metal",
      relleno: "No aplica",
      patas: "Patas ajustables de metal",
      tapizado: "No aplica",
      observaciones:
        "Fácil montaje sin herramientas. El valor de los decorados y detalles personalizados no incluido.",
    },
    available: true,
    categories: ["Almacenamiento"],
  },
  {
    id: 12,
    name: "Sillón de Terciopelo 2",
    description: "Un sillón moderno con acabado de terciopelo.",
    price: 3799900,
    discount: 0.1,
    images: [
      "/assets/sofa-terciopelo-azul-1.jpg",
      "/assets/estanteria.webp",
      "/assets/sofa-seccional.jpg",
      "/assets/cama-dosel.webp",
    ],
    information: {
      dimensiones: "80x80x90 cm",
      estructura: "Madera y metal",
      relleno: "Espuma de alta densidad",
      patas: "Madera de haya maciza",
      tapizado: "Tela de terciopelo",
      observaciones:
        "Disponible en varios colores. El valor de los decorados y detalles personalizados no incluido.",
    },
    available: true,
    categories: ["Sofás", "Sala de estar"],
  },
];
