### Recuperar todos los registros (películas)
GET http://localhost:3001/movies

### Recuperar un registro por id (películas)
GET http://localhost:3001/movies/:id

### Recuperar todos los registros por un género (películas)
GET http://localhost:3001/movies?genre=

### Crear una película con POST
POST http://localhost:3001/movies
Content-Type: application/json

### Actualizar una película con PATCH
PATCH http://localhost:3001/movies/1
Content-Type: application/json